/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.safestore.view;

/**
 *
 * @author Adrian Vizcaino <The-Softwarriors at ESPE>
 */
public class FrmMenuCashier extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuCashier.class.getName());

    /**
     * Creates new form FrmMenuCashier
     */
    public FrmMenuCashier() {
        initComponents();

     this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

     lblCashierTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
     lblCashierDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
     lblCashierLogged.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblCashierTitle = new javax.swing.JLabel();
        lblCashierDescription = new javax.swing.JLabel();
        lblCashierLogged = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFileCashier = new javax.swing.JMenu();
        itemExitCashier = new javax.swing.JMenuItem();
        Modules = new javax.swing.JMenu();
        itemCashControl = new javax.swing.JMenuItem();
        itemSalesSystem = new javax.swing.JMenuItem();
        Tools = new javax.swing.JMenu();
        itemKeyboardShortcutsCashier = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAboutCashier = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(775, 490));

        lblCashierTitle.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        lblCashierTitle.setText("WELCOME TO SAFESTORE");

        lblCashierDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCashierDescription.setText("Disposable Products Minimarket Management System");

        lblCashierLogged.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCashierLogged.setForeground(new java.awt.Color(51, 51, 255));
        lblCashierLogged.setText("Logged In As : Cashier");

        menuFileCashier.setText("File");

        itemExitCashier.setText("Exit");
        menuFileCashier.add(itemExitCashier);

        jMenuBar1.add(menuFileCashier);

        Modules.setText("Modules");

        itemCashControl.setText("Cash Control");
        Modules.add(itemCashControl);

        itemSalesSystem.setText("Sales System");
        Modules.add(itemSalesSystem);

        jMenuBar1.add(Modules);

        Tools.setText("Tools");

        itemKeyboardShortcutsCashier.setText("Keyboard Shortcuts");
        Tools.add(itemKeyboardShortcutsCashier);

        jMenuBar1.add(Tools);

        jMenu3.setText("Help");

        itemAboutCashier.setText("About");
        jMenu3.add(itemAboutCashier);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCashierTitle)
                    .addComponent(lblCashierDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCashierLogged, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblCashierTitle)
                .addGap(86, 86, 86)
                .addComponent(lblCashierDescription)
                .addGap(65, 65, 65)
                .addComponent(lblCashierLogged)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuCashier().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Modules;
    private javax.swing.JMenu Tools;
    private javax.swing.JMenuItem itemAboutCashier;
    private javax.swing.JMenuItem itemCashControl;
    private javax.swing.JMenuItem itemExitCashier;
    private javax.swing.JMenuItem itemKeyboardShortcutsCashier;
    private javax.swing.JMenuItem itemSalesSystem;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblCashierDescription;
    private javax.swing.JLabel lblCashierLogged;
    private javax.swing.JLabel lblCashierTitle;
    private javax.swing.JMenu menuFileCashier;
    // End of variables declaration//GEN-END:variables
}
