/*  
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.safestore.view;

/**
 *
 * @author Adrian Vizcaino <The-Softwarriors at ESPE>
 */
public class FrmMenuManager extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuManager.class.getName());

    /**
     * Creates new form FrmMenuManager
     */
    public FrmMenuManager() {
        initComponents();
      this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

     lblManagerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
     lblManagerDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
     lblManagerLogged.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        lblManagerTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblManagerDescription = new javax.swing.JLabel();
        lblManagerLogged = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFileManager = new javax.swing.JMenu();
        itmExitManager = new javax.swing.JMenuItem();
        menuModulesManager = new javax.swing.JMenu();
        itemAdaptativeUI = new javax.swing.JMenuItem();
        itemBackupSystem = new javax.swing.JMenuItem();
        itemCloudSync = new javax.swing.JMenuItem();
        itemCombos = new javax.swing.JMenuItem();
        itemCreditManagement = new javax.swing.JMenuItem();
        itemExpirationControl = new javax.swing.JMenuItem();
        itemProductManagement = new javax.swing.JMenuItem();
        itemReservations = new javax.swing.JMenuItem();
        itemSlowMovingReport = new javax.swing.JMenuItem();
        itemStockAlert = new javax.swing.JMenuItem();
        itemSupplierManagement = new javax.swing.JMenuItem();
        menuToolsManager = new javax.swing.JMenu();
        itemKeyboardShortcutsManager = new javax.swing.JMenuItem();
        menuHelpManager = new javax.swing.JMenu();
        itemAboutManager = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblManagerTitle.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        lblManagerTitle.setText("WELCOME TO SAFESTORE");

        lblManagerDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblManagerDescription.setText("Disposable Products Minimarket Management System");

        lblManagerLogged.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblManagerLogged.setForeground(new java.awt.Color(51, 51, 255));
        lblManagerLogged.setText("Logged In As : Manager");

        menuFileManager.setText("File");

        itmExitManager.setText("Exit");
        menuFileManager.add(itmExitManager);

        jMenuBar1.add(menuFileManager);

        menuModulesManager.setText("Modules");

        itemAdaptativeUI.setText("Adaptative UI");
        menuModulesManager.add(itemAdaptativeUI);

        itemBackupSystem.setText("Backup System");
        menuModulesManager.add(itemBackupSystem);

        itemCloudSync.setText("Cloud Sync");
        menuModulesManager.add(itemCloudSync);

        itemCombos.setText("Combos");
        menuModulesManager.add(itemCombos);

        itemCreditManagement.setText("Credit Management");
        itemCreditManagement.addActionListener(this::itemCreditManagementActionPerformed);
        menuModulesManager.add(itemCreditManagement);

        itemExpirationControl.setText("Expiration Control");
        menuModulesManager.add(itemExpirationControl);

        itemProductManagement.setText("Product Management");
        menuModulesManager.add(itemProductManagement);

        itemReservations.setText("Reservations");
        menuModulesManager.add(itemReservations);

        itemSlowMovingReport.setText("Slow Moving Report");
        itemSlowMovingReport.addActionListener(this::itemSlowMovingReportActionPerformed);
        menuModulesManager.add(itemSlowMovingReport);

        itemStockAlert.setText("Stock Alert");
        menuModulesManager.add(itemStockAlert);

        itemSupplierManagement.setText("Supplier Management");
        menuModulesManager.add(itemSupplierManagement);

        jMenuBar1.add(menuModulesManager);

        menuToolsManager.setText("Tools");

        itemKeyboardShortcutsManager.setText("Keyboard Shortcuts");
        menuToolsManager.add(itemKeyboardShortcutsManager);

        jMenuBar1.add(menuToolsManager);

        menuHelpManager.setText("Help");

        itemAboutManager.setText("About");
        menuHelpManager.add(itemAboutManager);

        jMenuBar1.add(menuHelpManager);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lblManagerTitle)
                        .addComponent(lblManagerDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblManagerLogged))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblManagerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(lblManagerDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(lblManagerLogged)
                .addGap(125, 125, 125))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreditManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreditManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCreditManagementActionPerformed

    private void itemSlowMovingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSlowMovingReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSlowMovingReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuManager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAboutManager;
    private javax.swing.JMenuItem itemAdaptativeUI;
    private javax.swing.JMenuItem itemBackupSystem;
    private javax.swing.JMenuItem itemCloudSync;
    private javax.swing.JMenuItem itemCombos;
    private javax.swing.JMenuItem itemCreditManagement;
    private javax.swing.JMenuItem itemExpirationControl;
    private javax.swing.JMenuItem itemKeyboardShortcutsManager;
    private javax.swing.JMenuItem itemProductManagement;
    private javax.swing.JMenuItem itemReservations;
    private javax.swing.JMenuItem itemSlowMovingReport;
    private javax.swing.JMenuItem itemStockAlert;
    private javax.swing.JMenuItem itemSupplierManagement;
    private javax.swing.JMenuItem itmExitManager;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblManagerDescription;
    private javax.swing.JLabel lblManagerLogged;
    private javax.swing.JLabel lblManagerTitle;
    private javax.swing.JMenu menuFileManager;
    private javax.swing.JMenu menuHelpManager;
    private javax.swing.JMenu menuModulesManager;
    private javax.swing.JMenu menuToolsManager;
    // End of variables declaration//GEN-END:variables
}
